## Handwritten Digit Recognition using LeNet-5 CNN Architecture on MNIST Digit Database

Handwritten Digit Recognition using the LeNet-5 CNN architecture on the MNIST dataset is a popular computer vision task. In this approach, we first load and preprocess the MNIST dataset, normalizing pixel values and one-hot encoding labels. Then, we define the LeNet-5 model, consisting of convolutional and fully connected layers. After compiling the model, we train it on the training data, evaluating its performance on the test set. Finally, we can make predictions using the trained model, achieving accurate recognition of handwritten digits.

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
from tensorflow.keras import datasets

In [3]:
datasets

<module 'keras.api._v2.keras.datasets' from 'C:\\Users\\mukes\\anaconda3\\Lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\__init__.py'>

## Training and testing Data

In [4]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

In [5]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
x_train.shape

(60000, 28, 28)

In [8]:
x_test.shape

(10000, 28, 28)

In [9]:
width, height = 28, 28
input_shape = (width, height, 1 )

In [10]:
input_shape

(28, 28, 1)

In [11]:
x_train = x_train.reshape(x_train.shape[0], height, width,1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

In [12]:
x_train.shape

(60000, 28, 28, 1)

In [13]:
y_train.shape

(60000,)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train,
                                                  test_size = 0.1)

In [16]:
len(x_train)

54000

In [17]:
len(x_val)

6000

## Feature Scaling 

In [18]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [19]:
x_train

array([[[[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]],

        [[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]],

        [[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]],

        ...,

        [[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]],

        [[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]],

        [[-0.42412306],
         [-0.42412306],
         [-0.42412306],
         ...,
         [-0.42412306],
         [-0.42412306],
         [-0.42412306]]],


       [[[-0.42412306],


In [20]:
from tensorflow import keras

In [21]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [22]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [23]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

## Model

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Input,Conv2D, MaxPooling2D, AveragePooling2D

In [25]:
model = Sequential()

In [26]:
model.add(Conv2D(6, kernel_size = (5,5), strides = (1,1), activation = 'tanh', input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size= (5,5), strides = (1,1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size= (2,2), strides = (1,1)))
model.add(Conv2D(120, kernel_size= (5,5), strides = (1,1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 23, 23, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 18, 18, 16)        0         
 gePooling2D)                                                    
                                                                 
 conv2d_2 (Conv2D)           (None, 14, 14, 120)       48120     
                                                                 
 flatten (Flatten)           (None, 23520)             0

In [28]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [29]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/20
1688/1688 [==============================] - 145s 85ms/step - loss: 0.2539 - accuracy: 0.9239 - val_loss: 0.2113 - val_accuracy: 0.9382
Epoch 2/20
1688/1688 [==============================] - 141s 84ms/step - loss: 0.1984 - accuracy: 0.9403 - val_loss: 0.1650 - val_accuracy: 0.9477
Epoch 3/20
1688/1688 [==============================] - 142s 84ms/step - loss: 0.1709 - accuracy: 0.9484 - val_loss: 0.1532 - val_accuracy: 0.9553
Epoch 4/20
1688/1688 [==============================] - 141s 84ms/step - loss: 0.1633 - accuracy: 0.9499 - val_loss: 0.1623 - val_accuracy: 0.9510
Epoch 5/20
1688/1688 [==============================] - 141s 84ms/step - loss: 0.1573 - accuracy: 0.9520 - val_loss: 0.1613 - val_accuracy: 0.9495
Epoch 6/20
1688/1688 [==============================] - 144s 85ms/step - loss: 0.1460 - accuracy: 0.9545 - val_loss: 0.1310 - val_accuracy: 0.9577
Epoch 7/20
1688/1688 [==============================] - 142s 84ms/step - loss: 0.1283 - accuracy: 0.9604 - val_loss: 0

In [32]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 4s 14ms/step - loss: 0.1086 - accuracy: 0.9679


In [33]:
score

[0.10861322283744812, 0.9678999781608582]