## Handwritten Digit Recognition using LeNet-5 CNN Architecture on MNIST Digit Database

Handwritten Digit Recognition using the LeNet-5 CNN architecture on the MNIST dataset is a popular computer vision task. In this approach, we first load and preprocess the MNIST dataset, normalizing pixel values and one-hot encoding labels. Then, we define the LeNet-5 model, consisting of convolutional and fully connected layers. After compiling the model, we train it on the training data, evaluating its performance on the test set. Finally, we can make predictions using the trained model, achieving accurate recognition of handwritten digits.

## Importing Libraries

In [2]:
import numpy as np
import pandas as pd

In [11]:
from tensorflow.keras import datasets

In [12]:
datasets

<module 'keras.api._v2.keras.datasets' from 'C:\\Users\\mukes\\anaconda3\\Lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\__init__.py'>

## Training and testing Data

In [13]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

In [14]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [16]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [17]:
x_train.shape

(60000, 28, 28)

In [18]:
x_test.shape

(10000, 28, 28)

In [19]:
width, height = 28, 28
input_shape = (width, height, 1 )

In [20]:
input_shape

(28, 28, 1)

In [21]:
x_train = x_train.reshape(x_train.shape[0], height, width,1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

In [22]:
x_train.shape

(60000, 28, 28, 1)

In [25]:
y_train.shape

(60000,)

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train,
                                                  test_size = 0.1)

In [29]:
len(x_train)

48600

In [30]:
len(x_val)

5400

## Feature Scaling 

In [32]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [33]:
x_train

array([[[[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]],

        [[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]],

        [[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]],

        ...,

        [[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]],

        [[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]],

        [[-0.42412437],
         [-0.42412437],
         [-0.42412437],
         ...,
         [-0.42412437],
         [-0.42412437],
         [-0.42412437]]],


       [[[-0.42412437],


In [35]:
from tensorflow import keras

In [38]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [39]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [40]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

## Model

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Input,Conv2D, MaxPooling2D, AveragePooling2D

In [56]:
model = Sequential()

In [57]:
model.add(Conv2D(6, kernel_size = (5,5), strides = (1,1), activation = 'tanh', input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size= (5,5), strides = (1,1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size= (2,2), strides = (1,1)))
model.add(Conv2D(120, kernel_size= (5,5), strides = (1,1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

In [58]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_5 (Conv2D)           (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_2 (Avera  (None, 23, 23, 6)         0         
 gePooling2D)                                                    
                                                                 
 conv2d_6 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_3 (Avera  (None, 18, 18, 16)        0         
 gePooling2D)                                                    
                                                                 
 conv2d_7 (Conv2D)           (None, 14, 14, 120)       48120     
                                                                 
 flatten_1 (Flatten)         (None, 23520)            

In [59]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [60]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/20
1519/1519 [==============================] - 124s 81ms/step - loss: 0.2476 - accuracy: 0.9262 - val_loss: 0.1830 - val_accuracy: 0.9463
Epoch 2/20
1519/1519 [==============================] - 121s 80ms/step - loss: 0.1991 - accuracy: 0.9399 - val_loss: 0.1821 - val_accuracy: 0.9433
Epoch 3/20
1519/1519 [==============================] - 121s 80ms/step - loss: 0.1868 - accuracy: 0.9433 - val_loss: 0.1691 - val_accuracy: 0.9493
Epoch 4/20
1519/1519 [==============================] - 121s 80ms/step - loss: 0.1554 - accuracy: 0.9531 - val_loss: 0.1410 - val_accuracy: 0.9557
Epoch 5/20
1519/1519 [==============================] - 123s 81ms/step - loss: 0.1505 - accuracy: 0.9543 - val_loss: 0.1233 - val_accuracy: 0.9626
Epoch 6/20
1519/1519 [==============================] - 126s 83ms/step - loss: 0.1390 - accuracy: 0.9571 - val_loss: 0.1274 - val_accuracy: 0.9626
Epoch 7/20
1519/1519 [==============================] - 128s 84ms/step - loss: 0.1431 - accuracy: 0.9564 - val_loss: 0

In [61]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 7s 23ms/step - loss: 0.0977 - accuracy: 0.9709


In [62]:
score

[0.09769131988286972, 0.9708999991416931]